language: php 

compiler:
  - gcc

os:
  - linux
#  - osx

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

notifications:
  email: nauxliu@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

sudo: true

before_install:
  - sudo apt-get install doxygen -y
  - sudo ./travis/install_opencc.sh

#Compile
before_script:
    - sudo ./travis/compile.sh

script:
    - exit 0
